# Adapted from https://github.com/commercialhaskell/stack
language: nix

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    - env: GHCVER=8.2.2 CACHE_NAME=8.2.2 BUILD_BINARY=1
      compiler: ": #stack 8.2.2"
      addons: {apt: {packages: [ghc-8.2.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.2-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.2.2"
      addons: {apt: {packages: [ghc-8.2.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.4.4 CACHE_NAME=8.4.4 BUILD_BINARY=1
      compiler: ": #stack 8.4.4"
      addons: {apt: {packages: [ghc-8.4.4], sources: [hvr-ghc]}}

    - env: GHCVER=8.4.4 CACHE_NAME=8.4.4-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.4.4"
      addons: {apt: {packages: [ghc-8.4.4], sources: [hvr-ghc]}}

    - env: GHCVER=8.6.2 CACHE_NAME=8.6.2 BUILD_BINARY=1
      compiler: ": #stack 8.6.2"
      addons: {apt: {packages: [ghc-8.6.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.4.4 CACHE_NAME=8.6.2-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.6.2"
      addons: {apt: {packages: [ghc-8.6.2], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   # Run tests
   stack --no-terminal test --ghc-options="$GHC_OPTIONS"
   set +ex

after_success:
 - |
   # Build and ship binary
   ./.travis/attach-binary.sh
