resolver: lts-19.6

packages:
  - '.'

extra-deps:
  - registry-0.3.0.5
  - tasty-1.4.2.3
  - git: "https://github.com/protolude/protolude"
    commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b

flags: {}

extra-package-dbs: []
