resolver: lts-12.21

packages:
- '.'

extra-deps:
  - registry-0.1.6.2
  - testing-type-modifiers-0.1.0.1

  - github: etorreborre/tasty-hedgehog
    commit: f11cd7b135ee374c8779abfd73117d041add12ec

  - git: git@github.com:etorreborre/haskell-hedgehog.git
    subdirs:
      - hedgehog
    commit: ab6cb116d688602a92f4c5319548e89d3813bbc5

flags: {}

extra-package-dbs: []
