resolver: lts-12.21

packages:
- '.'

extra-deps:
  - registry-0.1.4.2
  - testing-type-modifiers-0.1.0.1

  - github: etorreborre/tasty-hedgehog
    commit: f11cd7b135ee374c8779abfd73117d041add12ec

  - git: git@github.com:etorreborre/haskell-hedgehog.git
    subdirs:
      - hedgehog
    commit: a43d021dfcd8cf88f4a1e362f7d4e9c31132d26d

flags: {}

extra-package-dbs: []
